language: node_js
node_js:
   - "0.10"
   - "0.11"
matrix:
   allow_failures:
     - node_js: "0.11"
services:
  - mongodb
before_script:
  - sleep 10
  - echo mongo mongo_travis
script:
  - make travis
